/**
 * TriggerContext - Coordinates agent triggers and scheduling via Web Worker
 *
 * Sprint 11a Refactor: Moves execution to `agent.worker.ts`
 *
 * Responsibilities:
 * 1. Initialize Agent Worker
 * 2. Proxy user requests to worker
 * 3. Expose worker stats and status
 * 4. Maintain context interface for consumers
 */

import { createContext, useContext, type ReactNode } from 'react';
import type { MissionCard } from '@ownyou/shared-types';
import type { TriggerEngineStats, TriggerResult } from '@ownyou/triggers';
import { useAgentWorker } from '../hooks/useAgentWorker';

interface TriggerContextValue {
  /** Handle a user request (NL intent routing) */
  handleUserRequest: (request: string) => Promise<TriggerResult | null>;

  /** Check if trigger engine is running */
  isRunning: boolean;

  /** Start the trigger engine */
  start: () => void;

  /** Stop the trigger engine */
  stop: () => void;

  /** Get stats about trigger activity */
  getStats: () => TriggerEngineStats | null;

  /** Recent mission cards generated by agents */
  recentMissions: MissionCard[];

  /** Whether agents are currently executing */
  isExecuting: boolean;
}

const TriggerContext = createContext<TriggerContextValue | null>(null);

interface TriggerProviderProps {
  children: ReactNode;
}

export function TriggerProvider({ children }: TriggerProviderProps) {
  // Use the worker hook instead of local instantiation
  const { 
    isRunning, 
    stats, 
    handleUserRequest: workerHandleRequest, 
    start, 
    stop 
  } = useAgentWorker();

  // TODO: We need a way to get missions back from the worker
  // For now, we rely on the UI reading from the Store directly (which the worker writes to)
  const recentMissions: MissionCard[] = []; 

  const handleUserRequest = async (request: string): Promise<TriggerResult | null> => {
    try {
      return await workerHandleRequest(request);
    } catch (error) {
      console.error('[TriggerContext] Request failed:', error);
      return null;
    }
  };

  const getStats = () => stats;

  const value: TriggerContextValue = {
    handleUserRequest,
    isRunning,
    start,
    stop,
    getStats,
    recentMissions,
    isExecuting: false, // TODO: Add granular execution state to worker stats
  };

  return (
    <TriggerContext.Provider value={value}>
      {children}
    </TriggerContext.Provider>
  );
}

export function useTrigger() {
  const context = useContext(TriggerContext);
  if (!context) {
    throw new Error('useTrigger must be used within a TriggerProvider');
  }
  return context;
}

/**
 * Hook for handling user requests
 */
export function useAgentRequest() {
  const { handleUserRequest, isExecuting } = useTrigger();

  return {
    request: handleUserRequest,
    isLoading: isExecuting,
  };
}