// Auto-generated by generate-build-info.js - DO NOT EDIT
export const BUILD_INFO = {
  version: '0.1.15',
  buildTimestamp: '2025-12-18T17:24:06.746Z',
  buildDate: '18 Dec 2025, 17:24 GMT',
  gitCommit: '97f3a07',
  gitBranch: 'feature/sprint11c-ab-testing',
  buildNumber: 1766078646760
} as const;
