/**
 * Mission Card Types
 *
 * Type definitions for Mission Cards in OwnYou Consumer Application.
 * Mission Cards are generated by Mission Agents based on IAB classifications
 * and user data patterns.
 *
 * Based on Python models in src/models/complete_schema.py
 */

/**
 * Mission card types (corresponds to different Mission Agents)
 */
export enum CardType {
  SHOPPING = 'shopping',
  UTILITY = 'utility',
  SERVICES = 'services',
  TRAVEL = 'travel',
  EVENT = 'event',
  RESTAURANT = 'restaurant',
  RECIPE = 'recipe',
  CONTENT = 'content',
  HEALTH = 'health',
}

/**
 * High-level mission categories
 */
export enum CardCategory {
  SAVINGS = 'savings',
  IKIGAI = 'ikigai',
  HEALTH = 'health',
}

/**
 * Mission state lifecycle
 */
export enum MissionState {
  PENDING = 'pending',
  ACTIVE = 'active',
  SNOOZED = 'snoozed',
  COMPLETED = 'completed',
  DISMISSED = 'dismissed',
}

/**
 * Trigger types for mission creation
 */
export enum TriggerType {
  IAB_PROFILE_CHANGE = 'iab_profile_change',
  MANUAL = 'manual',
  SCHEDULED = 'scheduled',
  EVENT = 'event',
}

/**
 * Complexity levels for missions (Simple/Coordinated/Complex)
 */
export enum ComplexityLevel {
  SIMPLE = 1,      // Single-node agent, no coordination
  COORDINATED = 2, // Multi-node, some coordination
  COMPLEX = 3,     // Full ReAct loop, external tool use
}

/**
 * Agent types (corresponds to different Mission Agents)
 */
export enum AgentType {
  SHOPPING_AGENT = 'shopping_agent',
  TRAVEL_AGENT = 'travel_agent',
  RESTAURANT_AGENT = 'restaurant_agent',
  HEALTH_AGENT = 'health_agent',
  CONTENT_AGENT = 'content_agent',
}

/**
 * Mission Card - Base model for all mission types
 *
 * Every mission card contains these common fields regardless of type.
 * Type-specific data goes in the card_data field.
 */
export interface MissionCard {
  /** Unique identifier for this mission */
  mission_id: string

  /** User ID who owns this mission */
  user_id: string

  /** LangGraph thread ID for persistent conversation */
  thread_id: string

  /** Type of mission card */
  card_type: CardType

  /** Agent that created this mission */
  agent_type: AgentType

  /** High-level category */
  category: CardCategory

  /** Complexity level (Simple/Coordinated/Complex) */
  complexity_level: ComplexityLevel

  /** Current mission state */
  state: MissionState

  /** Trigger type that created this mission */
  trigger_type: TriggerType

  /** Trigger details (IAB classification, event, etc.) */
  trigger_details: Record<string, any>

  /** Memory context from Store (IAB classifications, user prefs, etc.) */
  memory_context: Record<string, any>

  /** Type-specific card data */
  card_data: Record<string, any>

  /** ISO timestamp when created */
  created_at: string

  /** ISO timestamp when last updated */
  updated_at: string

  /** Priority level (1-10, higher = more important) */
  priority: number

  /** User-facing title */
  title?: string

  /** User-facing description */
  description?: string

  /** Estimated completion time (minutes) */
  estimated_time?: number

  /** Tags for filtering/search */
  tags?: string[]
}

/**
 * Mission Agent Input - Trigger event for mission evaluation
 */
export interface MissionAgentInput {
  /** Trigger event type */
  trigger_type: TriggerType

  /** User ID to evaluate for */
  user_id: string

  /** Trigger-specific data */
  data: Record<string, any>
}

/**
 * Mission Agent Output - Result of mission evaluation
 */
export interface MissionAgentOutput {
  /** Whether mission was created */
  success: boolean

  /** Created mission card (if any) */
  card?: MissionCard

  /** Error message (if failed) */
  error?: string

  /** Reason for not creating mission */
  reason?: string
}

/**
 * Store namespace helpers for Mission Cards
 */
export function getMissionNamespace(userId: string): string[] {
  return [userId, 'mission_cards']
}

export function getMissionKey(missionId: string): string {
  return missionId
}

/**
 * Helper to create mission ID
 */
export function createMissionId(prefix: string = 'mission'): string {
  const randomHex = Math.random().toString(16).substring(2, 10)
  return `${prefix}_${randomHex}`
}

/**
 * Helper to create thread ID
 */
export function createThreadId(missionId: string): string {
  return `thread_${missionId}`
}
